### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by CodeLittlePrince** [monkeyWangs/Matting#1]
![image](https://cloud.githubusercontent.com/assets/17001245/25236220/e48d42b4-2619-11e7-876a-0e615b20f052.png)

**Comment by CodeLittlePrince** [comment]
应该改下
![image](https://cloud.githubusercontent.com/assets/17001245/25236822/6f929eb2-261b-11e7-9edb-33e03bbcd1f8.png)

**Comment by Ikkakuju** [comment]
@CodeLittlePrince 修改的没毛病😁

**Comment by muwoo** [comment]
已修复

**Comment by muwoo** [comment]
@CodeLittlePrince 感谢
